/// Flutter icons V_groups_icons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  V_groups_icons
///      fonts:
///       - asset: fonts/V_groups_icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class V_groups_icons {
  V_groups_icons._();

  static const _kFontFam = 'V_groups_icons';
  static const String? _kFontPkg = null;

  static const IconData helicopter = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about_1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
